### PR TITLE
feat: compsig script

### PR DESCRIPTION
**Pull request by jdev082**
this script compares signatures

### CODE REVIEW

**Comment by ninjamar** [comment]
Bash probably isn't the best tool for the antivirus

**Comment by UniqueName12345** [comment]
The owner has decided to use Python, so migrating to bash is a bad idea.

**Comment by jdev082** [comment]
Python can run bash scripts

**Comment by UniqueName12345** [comment]
> Python can run bash scripts

oh, in that case then

**Comment by jdev082** [comment]
I can port it to python if needed

**Comment by ninjamar** [comment]
> Python can run bash scripts

Why use `os.system` or `subprocess.run` when you can natively do it in python instead?

**Pull request merged**
